### ISSUE TITLE
posting videos not working

### ISSUE THREAD

**Issue by Zordon1337** [Lisa3000/videotube#3]
'-i' is not recognized as an internal or external command,
operable program or batch file.
'-i' is not recognized as an internal or external command,
operable program or batch file.
'-i' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Water-Boi** [comment]
did you install ffmpeg?

**Comment by Zordon1337** [comment]
i'm not using it anymore and it's been 8 months since i asked this question
